seed: 42
k_folds: 5
num_workers: 8

classes_to_count: [1, 2, 3, 4]

score_thresh_grid: [0.03, 0.05]

box_nms_thresh_grid: [0.28, 0.30, 0.32]

detections_per_image_grid: [280, 300, 320]

per_class_score_thresh_grid:
  - {"1": 0.18, "2": 0.18, "3": 0.18, "4": 0.18}
  - {"1": 0.20, "2": 0.20, "3": 0.20, "4": 0.20}
  - {"1": 0.22, "2": 0.22, "3": 0.22, "4": 0.22}